---

inherit_from: .rubocop_todo.yml

require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
